name: "Build and Deploy"

description: "Build all docker images and helm charts. 
  Creates a new branch named gha-{current-branch}. Then, creates a new commit replacing the chartVersion with the commit hash.
  If the branch already exists, then it will create only the new commit."

inputs:
  cci_token:
    description: 'CircleCI PAT used to trigger the pipeline. It must be a PAT instead of project token'
    required: true
  gh_pat:
    description: 'Github PAT used to trigger the pipeline. It must be a PAT instead of project token'
    required: true
  branch:
    description: 'Branch name used to build. It will be used the last commit available in this branch. Defaults to the branch triggering the workflow.'
    default: ${GITHUB_REF#refs/heads/}
    required: true
  reuse_branch:
    description: 'Reuse an existing branch -or- delete the existing branch and create a new one'
    default: false
  platform_branch:
    description: 'Name of the branch created in the platform-deployment repository. Defaults to gha-${current-branch-name}'
    default: gha-${GITHUB_REF##*/}
    required: true
  command:
    description: 'Command used in the commit message'
    default: '[deploy]'
    required: true
  apps:
    description: 'Target applications of the command in the commit message. E.g.: {lf,lo,iam}'
    required: true
  new_chart_version:
    description: 'Version committed in the chartVersion of the manifest file of the platform-deployment repository. Defaults to 0.0.0-{7-digits-commit-hash}'
    required: false
  chart_name:
    description: 'Name of the manifest chart file in the platform-repository.'
    required: true
  build_param:
    description: 'CircleCI parameter used to trigger the build action. Defaults to [build]'
    default: 'build'
  docker_build_job_name:
    description: 'Name of the product`s job that build and push the application`s docker image'
    required: true
    default: 'docker-build-and-push'


runs:
  using: composite
  steps:
    - name: 'Checkout actions'
      uses: actions/checkout@v3

    - name: 'Trigger CircleCI Build'
      uses: labforward/platform-gha/circleci/trigger@1.0.1
      with:
        cci_token: ${{ inputs.cci_token }}
        wait_for_cci_result: true
        build_param: ${{ inputs.build_param }}
        docker_build_job_name: ${{ inputs.docker_build_job_name }}

    - name: 'Create platform-deployment Branch'
      uses: labforward/platform-gha/platform/branch/create@1.1.0
      with:
        gh_pat: ${{ inputs.gh_pat }}
        apps: ${{ inputs.apps }}
        chart_name: ${{ inputs.chart_name }}
        reuse_branch: ${{ inputs.reuse_branch }}
