name: 'Dedupe Yarn Dependencies'
description: 'Run `yarn dedupe` and add a commit if necessary'

inputs:
  node-version:
    description: 'Version Spec of the version to use. Default: lts/*'
    default: 'lts/*'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: fregante/setup-git-user@v2
    - shell: bash
      run: corepack enable
    - uses: actions/setup-node@v6
      with:
        cache: yarn
        node-version: ${{ inputs.node-version }}

    - shell: bash
      env:
        HUSKY: 0
      run: |
        yarn dedupe

        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m '[dependabot skip] Dedupe dependencies'
          git push
        fi
